#!/usr/bin/env bash
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
ABSPATH=$(realpath $0)
BASEPATH=$(dirname ${ABSPATH})
PROJPATH=$(dirname $(dirname ${BASEPATH}))

echo "Running pre-commit hook scripts"
cd "${PROJPATH}"

echo "Running unit tests"
.scripts/test