#!/usr/bin/env bash
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}
ABSPATH=$(realpath $0)
BASEPATH=$(dirname ${ABSPATH})
PROJPATH=$(dirname ${BASEPATH})

cd "${PROJPATH}"

echo "Installing node modules"
npm install

echo "Installing scripts"
find .scripts -type f -not -path ".scripts/template/*" -exec chmod +x {} \;
find .scripts -type d -exec chmod 775 {} \;

echo "Installing development tools"
"${PROJPATH}/.scripts/include/install_dev_tools.sh"

echo "Ignoring changes for configuration files"
git update-index --assume-unchanged src/tests/test-config.ts

echo "Installing git hooks"
cp "${PROJPATH}/.scripts/template/pre-commit" "${PROJPATH}/.git/hooks/pre-commit"
cp "${PROJPATH}/.scripts/template/post-merge" "${PROJPATH}/.git/hooks/post-merge"
chmod +x "${PROJPATH}/.git/hooks/pre-commit"
chmod +x "${PROJPATH}/.git/hooks/post-merge"

echo "Configuring API"
"${PROJPATH}/.scripts/configure"

# Run tests
"${PROJPATH}/.scripts/include/run_tests_dialog.sh"

echo "Installation complete!"